# application.yml
server:
  port: 8080
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
tencent-cloud:
  cos:
    secretId: AKIDCuX8kE2jEjCaBcrw33rSq23ta4KPK1Uk
    secretKey: AIEwTt66vZ0EF4g5JMDtMb3OWQ7apqdN
    bucketId: se-project-1301778434
    regionName: ap-beijing
spring:
  application:
    name: defake-logi-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://122.9.35.116:3306/testdb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ruangong-6-mysql-passwd
  mail:
    host: smtp.163.com       # 以QQ邮箱为例
    port: 994
    username: gordonhemu@163.com   # 发件人邮箱
    password: JHbB8gtymCj4ndAx # QQ邮箱授权码（非登录密码）
    protocol: smtp
    properties:
      mail:
        smtp:
          ssl:
            enable: true